### ISSUE TITLE
Request to the Resend API failed. Reason: Syntax error

### ISSUE THREAD

**Issue by flatcapco** [resend/resend-laravel#71]
I've reported this to resend via the message box but also reporting here.

I've got fairly standard mailables in my laravel 11 project. Every 100 emails or so I get this random error. Its happened 3x now and on different mailables. Because my jobs are set to retry a few times, this always goes out successfully on the 2nd try.

Which is even more confusing because if there was truly a syntax error we'd have another fail?

There is nothing for the fail in the resend log gui.

And I'm having a hard time where I can take it from here. 

Using these versions:
"resend/resend-laravel": "^0.14.0",
"laravel/framework": "^11.33",

**Comment by flatcapco** [comment]
Just spotted this stacktrace in Horizon that I thought might be helpful:

`JsonException: Syntax error in /vendor/resend/resend-php/src/Transporters/HttpTransporter.php:70
Stack trace:
#0 /vendor/resend/resend-php/src/Transporters/HttpTransporter.php(70): json_decode('...', true, 512, 4194304)
#1 /vendor/resend/resend-php/src/Transporters/HttpTransporter.php(49): Resend\Transporters\HttpTransporter->throwIfJsonError(Object(GuzzleHttp\Psr7\Response), '...')
#2 /vendor/resend/resend-php/src/Service/Email.php(32): Resend\Transporters\HttpTransporter->request(Object(Resend\ValueObjects\Transporter\Payload))
#3 /vendor/resend/resend-php/src/Service/Email.php(44): Resend\Service\Email->create(Array)
#4 /vendor/resend/resend-laravel/src/Transport/ResendTransportFactory.php(62): Resend\Service\Email->send(Array)
#5 /vendor/symfony/mailer/Transport/AbstractTransport.php(69): Resend\Laravel\Transport\ResendTransportFactory->doSend(Object(Symfony\Component\Mailer\SentMessage))
#6 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(585): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#7 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(332): Illuminate\Mail\Mailer->sendSymfonyMessage(Object(Symfony\Component\Mime\Email))
#8 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(205): Illuminate\Mail\Mailer->send(Object(Closure), Array, Object(Closure))
#9 /vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#10 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(198): Illuminate\Mail\Mailable->withLocale(NULL, Object(Closure))
#11 /vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(83): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\MailManager))
#12 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Mail\SendQueuedMailable->handle(Object(Illuminate\Mail\MailManager))
#13 /vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#18 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#19 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#20 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Mail\SendQueuedMailable), false)
#22 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#24 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Mail\SendQueuedMailable))
#26 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#27 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(441): Illuminate\Queue\Jobs\Job->fire()
#28 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(391): Illuminate\Queue\Worker->process('...', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#29 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(178): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), '...', Object(Illuminate\Queue\WorkerOptions))
#30 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon('...', '...', Object(Illuminate\Queue\WorkerOptions))
#31 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker('...', '...')
#32 /vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#33 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#34 /vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#35 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#36 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#37 /vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#38 /vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call(Array)
#39 /vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /vendor/symfony/console/Application.php(1047): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1205): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /artisan(13): Illuminate\Foundation\Application->handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
#47 {main}
Next Resend\Exceptions\UnserializableResponse: Syntax error in /vendor/resend/resend-php/src/Transporters/HttpTransporter.php:79
Stack trace:
#0 /vendor/resend/resend-php/src/Transporters/HttpTransporter.php(49): Resend\Transporters\HttpTransporter->throwIfJsonError(Object(GuzzleHttp\Psr7\Response), '...')
#1 /vendor/resend/resend-php/src/Service/Email.php(32): Resend\Transporters\HttpTransporter->request(Object(Resend\ValueObjects\Transporter\Payload))
#2 /vendor/resend/resend-php/src/Service/Email.php(44): Resend\Service\Email->create(Array)
#3 /vendor/resend/resend-laravel/src/Transport/ResendTransportFactory.php(62): Resend\Service\Email->send(Array)
#4 /vendor/symfony/mailer/Transport/AbstractTransport.php(69): Resend\Laravel\Transport\ResendTransportFactory->doSend(Object(Symfony\Component\Mailer\SentMessage))
#5 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(585): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#6 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(332): Illuminate\Mail\Mailer->sendSymfonyMessage(Object(Symfony\Component\Mime\Email))
#7 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(205): Illuminate\Mail\Mailer->send(Object(Closure), Array, Object(Closure))
#8 /vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#9 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(198): Illuminate\Mail\Mailable->withLocale(NULL, Object(Closure))
#10 /vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(83): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\MailManager))
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Mail\SendQueuedMailable->handle(Object(Illuminate\Mail\MailManager))
#12 /vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#17 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#18 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#19 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Mail\SendQueuedMailable), false)
#21 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#22 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#23 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Mail\SendQueuedMailable))
#25 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#26 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(441): Illuminate\Queue\Jobs\Job->fire()
#27 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(391): Illuminate\Queue\Worker->process('...', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#28 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(178): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), '...', Object(Illuminate\Queue\WorkerOptions))
#29 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon('...', '...', Object(Illuminate\Queue\WorkerOptions))
#30 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker('...', '...')
#31 /vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#32 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#33 /vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#35 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#36 /vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#37 /vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call(Array)
#38 /vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#39 /vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /vendor/symfony/console/Application.php(1047): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1205): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /artisan(13): Illuminate\Foundation\Application->handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
#46 {main}
Next Symfony\Component\Mailer\Exception\TransportException: Request to the Resend API failed. Reason: Syntax error in /vendor/resend/resend-laravel/src/Transport/ResendTransportFactory.php:75
Stack trace:
#0 /vendor/symfony/mailer/Transport/AbstractTransport.php(69): Resend\Laravel\Transport\ResendTransportFactory->doSend(Object(Symfony\Component\Mailer\SentMessage))
#1 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(585): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#2 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(332): Illuminate\Mail\Mailer->sendSymfonyMessage(Object(Symfony\Component\Mime\Email))
#3 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(205): Illuminate\Mail\Mailer->send(Object(Closure), Array, Object(Closure))
#4 /vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#5 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(198): Illuminate\Mail\Mailable->withLocale(NULL, Object(Closure))
#6 /vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(83): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\MailManager))
#7 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Mail\SendQueuedMailable->handle(Object(Illuminate\Mail\MailManager))
#8 /vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#13 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#15 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Mail\SendQueuedMailable), false)
#17 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#18 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#19 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Mail\SendQueuedMailable))
#21 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#22 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(441): Illuminate\Queue\Jobs\Job->fire()
#23 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(391): Illuminate\Queue\Worker->process('...', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#24 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(178): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), '...', Object(Illuminate\Queue\WorkerOptions))
#25 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon('...', '...', Object(Illuminate\Queue\WorkerOptions))
#26 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker('...', '...')
#27 /vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#28 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#29 /vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#31 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#32 /vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#33 /vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call(Array)
#34 /vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#35 /vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#36 /vendor/symfony/console/Application.php(1047): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1205): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /artisan(13): Illuminate\Foundation\Application->handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
#42 {main}`

**Comment by SahinU88** [comment]
@flatcapco are you using the batch-mail api by a chance?

I had the same issue when I wanted to send batch-mails via resend.

example code:

```php
$mails = $users->map(function ($user) {
    $mail = new MailClass($params); // as an example

    return [
        'from' => "...",
        'to' => [ "..."],
        'subject' =>  "...",
        'html' =>  "...",
    ];
});

// the batch API endpoint allows 100 mails at once at most
$mails->chunk(100)->each(function($chunk){
  $resend->batch->send($chunk->toArray());
});
```

with the snippet above the first call was always successful but all the following requests got an error:

```json
{
    "name": "validation_error",
    "message": "The `request.body` field must be an `array`.",
    "statusCode": 422
}
```

I then noticed that the index of the array chunks caused the issue. If the array doesn't start at 0, the request body is handled as an object instead of an array. 

By changing

```php
$mails->chunk(100)->each(function ($chunk) use ($resend) {
    $batch = $chunk->values()->toArray(); // resetting the array-index
    $resend->batch->send($batch);
});
```

the batch-mails worked as expected.

**Comment by flatcapco** [comment]
Hey @SahinU88 I'm not using batch mail sadly so that doesn't fix it they are all queued up a separate mails

**Comment by SahinU88** [comment]
Not sure if I can help but could you provide a code snippet showing how you use the mail service?

**Comment by opheus2** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f0519597-dc0c-4a6d-95dd-6d76b9ab9c93" />
Hi, We are also facing the same issue. We have had these errors over 143 times now. 

Just like @flatcapco mentioned, it happens randomly and it doesn't add up because all other emails should fail ideally.

**Comment by Cannonb4ll** [comment]
This exception has been bugging me for so long as well, that I have decided to mute it for now in my exception handler 🤷‍♂️

**Comment by wassim** [comment]
Having this error too, did anyone managed to resolve it?

**Comment by flatcapco** [comment]
Nope I was told its a bigger problem that they are working hard to fix.

**Comment by austincarpenter** [comment]
Good to know it's not just us. We're up to 87.

![Image](https://github.com/user-attachments/assets/26d89352-f5a3-42ca-b4b4-6a3dfd980d6c)

**Comment by jayanratna** [comment]
Hi all, I have been experimenting with better error handling for non-JSON errors. Let me know what you think.

https://github.com/resend/resend-php/pull/77

**Comment by jayanratna** [comment]
Marking this as complete. Please let me know if this issue still occurs on the latest version of the library (`v0.23.0`).
